# Generated by Django 3.1.2 on 2020-12-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginModel',
            new_name='Login_Page',
        ),
    ]
